version: '3.7'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    links:
      - postgres_db:database

  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app_db